<?php

/**
 * Implements hook_theme().
 */

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return \string[][]
 *
 * Implements hook_theme
 */
function upload_image_theme($existing, $type, $theme, $path) {
  return [
    'upload_image_registration_form' => [
      'render element' => 'form',
    ]
  ];
}

function upload_image_page_attachments_alter(array &$page) {
  $path = \Drupal::service('path.current')->getPath();
  if( strpos($path, '/manage-appearance') > -1 ) {
    $page['#attached']['library'][] = 'upload_image/upload-lib';
  }
}

function upload_image_preprocess_page(&$vars) {
  // replace the site logo 
  $roles = \Drupal::currentUser()->getRoles();
  // if(in_array('institute', $roles) || in_array('instructor', $roles)) {
    
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    if( !empty($user->get("field_institution")->first()) ){
      $item = $user->get("field_institution")->first()->getValue();
      $nid = $item['target_id'];
    }

    if($nid > 0) {
      $load_node = \Drupal\node\Entity\Node::load($nid);
      if( is_object($load_node) ) {
        if( $load_node->get('field_logo')->entity ) {
          $logo_uri = $load_node->get('field_logo')->entity->getFileUri();
          $logo_path = file_create_url($logo_uri);
          $logo_hyperlink = $load_node->get('field_logo_hyperlink')->value;
          $vars['institution_logo'] = $logo_path;
        }
      }
      $vars['institution_logo_hyperlink'] = $logo_hyperlink;
    }
  // }
  // dump($vars);
}
